// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: protos/types/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationType int32

const (
	NotificationType_SMS  NotificationType = 0
	NotificationType_PUSH NotificationType = 1
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "SMS",
		1: "PUSH",
	}
	NotificationType_value = map[string]int32{
		"SMS":  0,
		"PUSH": 1,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_types_types_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_protos_types_types_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_protos_types_types_proto_rawDescGZIP(), []int{0}
}

type NotificationLog struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserOsaFeedbackId int64                  `protobuf:"varint,1,opt,name=user_osa_feedback_id,json=userOsaFeedbackId,proto3" json:"user_osa_feedback_id,omitempty"`
	UserId            uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OsaId             uint64                 `protobuf:"varint,3,opt,name=osa_id,json=osaId,proto3" json:"osa_id,omitempty"`
	OnlineGroupId     int64                  `protobuf:"varint,4,opt,name=online_group_id,json=onlineGroupId,proto3" json:"online_group_id,omitempty"`
	NotificationType  NotificationType       `protobuf:"varint,5,opt,name=notification_type,json=notificationType,proto3,enum=errors.NotificationType" json:"notification_type,omitempty"`
	SendTimes         uint32                 `protobuf:"varint,6,opt,name=send_times,json=sendTimes,proto3" json:"send_times,omitempty"`
	SendDays          uint32                 `protobuf:"varint,7,opt,name=send_days,json=sendDays,proto3" json:"send_days,omitempty"`
	TimestampSecs     uint32                 `protobuf:"varint,8,opt,name=timestamp_secs,json=timestampSecs,proto3" json:"timestamp_secs,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NotificationLog) Reset() {
	*x = NotificationLog{}
	mi := &file_protos_types_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationLog) ProtoMessage() {}

func (x *NotificationLog) ProtoReflect() protoreflect.Message {
	mi := &file_protos_types_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationLog.ProtoReflect.Descriptor instead.
func (*NotificationLog) Descriptor() ([]byte, []int) {
	return file_protos_types_types_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationLog) GetUserOsaFeedbackId() int64 {
	if x != nil {
		return x.UserOsaFeedbackId
	}
	return 0
}

func (x *NotificationLog) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *NotificationLog) GetOsaId() uint64 {
	if x != nil {
		return x.OsaId
	}
	return 0
}

func (x *NotificationLog) GetOnlineGroupId() int64 {
	if x != nil {
		return x.OnlineGroupId
	}
	return 0
}

func (x *NotificationLog) GetNotificationType() NotificationType {
	if x != nil {
		return x.NotificationType
	}
	return NotificationType_SMS
}

func (x *NotificationLog) GetSendTimes() uint32 {
	if x != nil {
		return x.SendTimes
	}
	return 0
}

func (x *NotificationLog) GetSendDays() uint32 {
	if x != nil {
		return x.SendDays
	}
	return 0
}

func (x *NotificationLog) GetTimestampSecs() uint32 {
	if x != nil {
		return x.TimestampSecs
	}
	return 0
}

var File_protos_types_types_proto protoreflect.FileDescriptor

const file_protos_types_types_proto_rawDesc = "" +
	"\n" +
	"\x18protos/types/types.proto\x12\x06errors\"\xc4\x02\n" +
	"\x0fNotificationLog\x12/\n" +
	"\x14user_osa_feedback_id\x18\x01 \x01(\x03R\x11userOsaFeedbackId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x15\n" +
	"\x06osa_id\x18\x03 \x01(\x04R\x05osaId\x12&\n" +
	"\x0fonline_group_id\x18\x04 \x01(\x03R\ronlineGroupId\x12E\n" +
	"\x11notification_type\x18\x05 \x01(\x0e2\x18.errors.NotificationTypeR\x10notificationType\x12\x1d\n" +
	"\n" +
	"send_times\x18\x06 \x01(\rR\tsendTimes\x12\x1b\n" +
	"\tsend_days\x18\a \x01(\rR\bsendDays\x12%\n" +
	"\x0etimestamp_secs\x18\b \x01(\rR\rtimestampSecs*%\n" +
	"\x10NotificationType\x12\a\n" +
	"\x03SMS\x10\x00\x12\b\n" +
	"\x04PUSH\x10\x01B\x1fZ\x1dgithub.com/x/protos/lib/typesb\x06proto3"

var (
	file_protos_types_types_proto_rawDescOnce sync.Once
	file_protos_types_types_proto_rawDescData []byte
)

func file_protos_types_types_proto_rawDescGZIP() []byte {
	file_protos_types_types_proto_rawDescOnce.Do(func() {
		file_protos_types_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_types_types_proto_rawDesc), len(file_protos_types_types_proto_rawDesc)))
	})
	return file_protos_types_types_proto_rawDescData
}

var file_protos_types_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_types_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_types_types_proto_goTypes = []any{
	(NotificationType)(0),   // 0: errors.NotificationType
	(*NotificationLog)(nil), // 1: errors.NotificationLog
}
var file_protos_types_types_proto_depIdxs = []int32{
	0, // 0: errors.NotificationLog.notification_type:type_name -> errors.NotificationType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_types_types_proto_init() }
func file_protos_types_types_proto_init() {
	if File_protos_types_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_types_types_proto_rawDesc), len(file_protos_types_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_types_types_proto_goTypes,
		DependencyIndexes: file_protos_types_types_proto_depIdxs,
		EnumInfos:         file_protos_types_types_proto_enumTypes,
		MessageInfos:      file_protos_types_types_proto_msgTypes,
	}.Build()
	File_protos_types_types_proto = out.File
	file_protos_types_types_proto_goTypes = nil
	file_protos_types_types_proto_depIdxs = nil
}
